### ISSUE TITLE
Cant run python example 

### ISSUE THREAD

**Issue by gavr123456789** [aluntzer/gtknodes#4]
```
sh-5.0$ GI_TYPELIB_PATH=../src/ LD_LIBRARY_PATH=../src/  python img.py 

** (img.py:42164): WARNING **: 12:52:20.807: Failed to load shared library 'libgtknodes-0.1.so.0' referenced by the typelib: libgtknodes-0.1.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
/usr/lib/python3.8/site-packages/gi/types.py:220: Warning: cannot derive 'SrcNode' from non-derivable parent type 'void'
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "img.py", line 43, in <module>
    class ImgSrcNode(GtkNodes.Node):
  File "/usr/lib/python3.8/site-packages/gi/types.py", line 229, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib/python3.8/site-packages/gi/types.py", line 208, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib/python3.8/site-packages/gi/types.py", line 220, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create new GType: SrcNode (subclass of void)

```
Also C demo works good.

**Comment by aluntzer** [comment]
try GI_TYPELIB_PATH=../src/ LD_LIBRARY_PATH=../src/.libs  python img.py

**Comment by gavr123456789** [comment]
Ty, works now.
